const PHOTOS_COUNT = 25;
const COMMENTS_COUNT = 5;
const MAX_HASHTAG_COUNT = 5;
const MAX_DESCRIPTION_SYMBOLS_COUNT = 140;

export {
  PHOTOS_COUNT,
  COMMENTS_COUNT,
  MAX_HASHTAG_COUNT,
  MAX_DESCRIPTION_SYMBOLS_COUNT
};
